---
---


## 지역별 시계열 시각화

```{r}
load("../refinedata/analysis/analysis_total.rda")
library(dplyr)

```


# 발생건수 전체

```{r}

analysis_sido_day <- analysis_total  %>% group_by(일시) %>% summarise(발생건수 = mean(발생건수,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$발생건수,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '발생건수 전체')



```

# 발생건수 서울

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='서울')  %>% group_by(일시) %>% summarise(발생건수 = mean(발생건수,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$발생건수,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '발생건수 서울')



```

# 발생건수 부산

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='부산')  %>% group_by(일시) %>% summarise(발생건수 = mean(발생건수,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$발생건수,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '발생건수 부산')


```

# 발생건수 대구

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='대구')  %>% group_by(일시) %>% summarise(발생건수 = mean(발생건수,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$발생건수,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '발생건수 대구')


```


# 발생건수 인천

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='인천')  %>% group_by(일시) %>% summarise(발생건수 = mean(발생건수,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$발생건수,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '발생건수 인천')



```

# 발생건수 광주

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='광주')  %>% group_by(일시) %>% summarise(발생건수 = mean(발생건수,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$발생건수,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '발생건수 광주')



```


# 발생건수 대전

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='대전')  %>% group_by(일시) %>% summarise(발생건수 = mean(발생건수,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$발생건수,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '발생건수 대전')



```

# 발생건수 울산

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='울산')  %>% group_by(일시) %>% summarise(발생건수 = mean(발생건수,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$발생건수,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '발생건수 울산')



```

# 발생건수 세종

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='세종')  %>% group_by(일시) %>% summarise(발생건수 = mean(발생건수,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$발생건수,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '발생건수 세종')



```

# 발생건수 제주

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='제주')  %>% group_by(일시) %>% summarise(발생건수 = mean(발생건수,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$발생건수,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '발생건수 제주')



```

# 발생건수 경기

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='경기')  %>% group_by(일시) %>% summarise(발생건수 = mean(발생건수,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$발생건수,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '발생건수 경기')



```

# 발생건수 강원

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='강원')  %>% group_by(일시) %>% summarise(발생건수 = mean(발생건수,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$발생건수,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '발생건수 강원')



```

# 발생건수 충북

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='충북')  %>% group_by(일시) %>% summarise(발생건수 = mean(발생건수,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$발생건수,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '발생건수 충북')



```

# 발생건수 충남

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='충남')  %>% group_by(일시) %>% summarise(발생건수 = mean(발생건수,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$발생건수,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '발생건수 충남')



```

# 발생건수 전북

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='전북')  %>% group_by(일시) %>% summarise(발생건수 = mean(발생건수,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$발생건수,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '발생건수 전북')


```

# 발생건수 전남

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='전남')  %>% group_by(일시) %>% summarise(발생건수 = mean(발생건수,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$발생건수,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '발생건수 전남')


```

# 발생건수 경북

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='경북')  %>% group_by(일시) %>% summarise(발생건수 = mean(발생건수,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$발생건수,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '발생건수 경북')


```

# 발생건수 경남

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='경남')  %>% group_by(일시) %>% summarise(발생건수 = mean(발생건수,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$발생건수,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '발생건수 경남')



```

