---
---


## 지역별 시계열 시각화

```{r}
load("../../refinedata/analysis/analysis_total.rda")
library(dplyr)

```


# 이산화 질소 전체

```{r}

analysis_sido_day <- analysis_total  %>% group_by(일시) %>% summarise(NO2 = mean(NO2,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$NO2,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '이산화질소 전체')



```

# 이산화 질소 서울

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='서울')  %>% group_by(일시) %>% summarise(NO2 = mean(NO2,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$NO2,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '이산화질소 서울')



```

# 이산화 질소 부산

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='부산')  %>% group_by(일시) %>% summarise(NO2 = mean(NO2,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$NO2,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '이산화질소 부산')



```

# 이산화 질소 대구

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='대구')  %>% group_by(일시) %>% summarise(NO2 = mean(NO2,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$NO2,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '이산화질소 대구')



```


# 이산화 질소 인천

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='인천')  %>% group_by(일시) %>% summarise(NO2 = mean(NO2,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$NO2,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '이산화질소 인천')



```

# 이산화 질소 광주

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='광주')  %>% group_by(일시) %>% summarise(NO2 = mean(NO2,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$NO2,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '이산화질소 광주')



```


# 이산화 질소 대전

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='대전')  %>% group_by(일시) %>% summarise(NO2 = mean(NO2,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$NO2,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '이산화질소 대전')



```

# 이산화 질소 울산

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='울산')  %>% group_by(일시) %>% summarise(NO2 = mean(NO2,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$NO2,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '이산화질소 울산')



```

# 이산화 질소 세종

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='세종')  %>% group_by(일시) %>% summarise(NO2 = mean(NO2,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$NO2,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '이산화질소 세종')



```

# 이산화 질소 제주

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='제주')  %>% group_by(일시) %>% summarise(NO2 = mean(NO2,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$NO2,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '이산화질소 제주')



```

# 이산화 질소 경기

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='경기')  %>% group_by(일시) %>% summarise(NO2 = mean(NO2,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$NO2,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '이산화질소 경기')



```

# 이산화 질소 강원

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='강원')  %>% group_by(일시) %>% summarise(NO2 = mean(NO2,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$NO2,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '이산화질소 강원')



```

# 이산화 질소 충북

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='충북')  %>% group_by(일시) %>% summarise(NO2 = mean(NO2,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$NO2,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '이산화질소 충북')



```

# 이산화 질소 충남

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='충남')  %>% group_by(일시) %>% summarise(NO2 = mean(NO2,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$NO2,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '이산화질소 충남')



```

# 이산화 질소 전북

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='전북')  %>% group_by(일시) %>% summarise(NO2 = mean(NO2,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$NO2,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '이산화질소 전북')



```

# 이산화 질소 전남

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='전남')  %>% group_by(일시) %>% summarise(NO2 = mean(NO2,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$NO2,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '이산화질소 전남')



```

# 이산화 질소 경북

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='경북')  %>% group_by(일시) %>% summarise(NO2 = mean(NO2,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$NO2,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '이산화질소 경북')



```

# 이산화 질소 경남

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='경남')  %>% group_by(일시) %>% summarise(NO2 = mean(NO2,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$NO2,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '이산화질소 경남')



```

