---
---


## 지역별 시계열 시각화

```{r}
load("../../refinedata/analysis/analysis_total.rda")
library(dplyr)

```


# `평균기온(°C)` 전체

```{r}

analysis_sido_day <- analysis_total  %>% group_by(일시) %>% summarise(`평균기온(°C)` = mean(`평균기온(°C)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균기온(°C)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균기온(°C)` 전체')



```

# `평균기온(°C)` 서울

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='서울')  %>% group_by(일시) %>% summarise(`평균기온(°C)` = mean(`평균기온(°C)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균기온(°C)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균기온(°C)` 서울')



```

# `평균기온(°C)` 부산

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='부산')  %>% group_by(일시) %>% summarise(`평균기온(°C)` = mean(`평균기온(°C)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균기온(°C)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균기온(°C)` 부산')


```

# `평균기온(°C)` 대구

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='대구')  %>% group_by(일시) %>% summarise(`평균기온(°C)` = mean(`평균기온(°C)`,na.rm=TRUE))

ts <- ts(na.omit(analysis_sido_day[-1])$`평균기온(°C)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균기온(°C)` 대구')


```


# `평균기온(°C)` 인천

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='인천')  %>% group_by(일시) %>% summarise(`평균기온(°C)` = mean(`평균기온(°C)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균기온(°C)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균기온(°C)` 인천')



```

# `평균기온(°C)` 광주

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='광주')  %>% group_by(일시) %>% summarise(`평균기온(°C)` = mean(`평균기온(°C)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균기온(°C)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균기온(°C)` 광주')



```


# `평균기온(°C)` 대전

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='대전')  %>% group_by(일시) %>% summarise(`평균기온(°C)` = mean(`평균기온(°C)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균기온(°C)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균기온(°C)` 대전')



```

# `평균기온(°C)` 울산

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='울산')  %>% group_by(일시) %>% summarise(`평균기온(°C)` = mean(`평균기온(°C)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균기온(°C)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균기온(°C)` 울산')



```

# `평균기온(°C)` 세종

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='세종')  %>% group_by(일시) %>% summarise(`평균기온(°C)` = mean(`평균기온(°C)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균기온(°C)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균기온(°C)` 세종')



```

# `평균기온(°C)` 제주

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='제주')  %>% group_by(일시) %>% summarise(`평균기온(°C)` = mean(`평균기온(°C)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균기온(°C)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균기온(°C)` 제주')



```

# `평균기온(°C)` 경기

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='경기')  %>% group_by(일시) %>% summarise(`평균기온(°C)` = mean(`평균기온(°C)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균기온(°C)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균기온(°C)` 경기')



```

# `평균기온(°C)` 강원

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='강원')  %>% group_by(일시) %>% summarise(`평균기온(°C)` = mean(`평균기온(°C)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균기온(°C)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균기온(°C)` 강원')



```

# `평균기온(°C)` 충북

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='충북')  %>% group_by(일시) %>% summarise(`평균기온(°C)` = mean(`평균기온(°C)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균기온(°C)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균기온(°C)` 충북')



```

# `평균기온(°C)` 충남

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='충남')  %>% group_by(일시) %>% summarise(`평균기온(°C)` = mean(`평균기온(°C)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균기온(°C)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균기온(°C)` 충남')



```

# `평균기온(°C)` 전북

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='전북')  %>% group_by(일시) %>% summarise(`평균기온(°C)` = mean(`평균기온(°C)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균기온(°C)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균기온(°C)` 전북')


```

# `평균기온(°C)` 전남

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='전남')  %>% group_by(일시) %>% summarise(`평균기온(°C)` = mean(`평균기온(°C)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균기온(°C)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균기온(°C)` 전남')


```

# `평균기온(°C)` 경북

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='경북')  %>% group_by(일시) %>% summarise(`평균기온(°C)` = mean(`평균기온(°C)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균기온(°C)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균기온(°C)` 경북')


```

# `평균기온(°C)` 경남

```{r}

analysis_sido_day <- analysis_total %>% filter(시도=='경남')  %>% group_by(일시) %>% summarise(`평균기온(°C)` = mean(`평균기온(°C)`,na.rm=TRUE))

ts <- ts(analysis_sido_day[-1]$`평균기온(°C)`,frequency = 365, start = c(2016,1))

fit <- stl(ts, s.window = 'periodic')

par(mfrow=c(1,1))

plot(fit,
     main = '`평균기온(°C)` 경남')



```

