---
---

```{r include=FALSE}
library(readr)
library(readxl)
library(dplyr)
library(stringr)

#-----------------------------------------
#데이터 가져오기
#----------------------------------------


colnames <- c('지역','측정소코드','측정소명','측정일시','SO2','CO','O3','NO2','PM10','PM25','주소')
df_concat<- read_csv('../lawdata/dust/2016/2016년 1분기.csv',locale=locale('ko',encoding='euc-kr'))
df_concat <- df_concat[colnames]

for(i in c(2:4)){
  df_input <- read_csv(paste('../lawdata/dust/2016/2016년 ',i,'분기.csv',sep=''),locale=locale('ko',encoding='euc-kr'))
  df_input <- df_input[colnames]
  df_concat <-rbind(df_concat,df_input)
}
for(i in c(1:4)){
  df_input <- read_excel(paste('../lawdata/dust/2017/2017년 ',i,'분기.xlsx',sep=''))
  df_input <- df_input[colnames]
  df_concat <-rbind(df_concat,df_input)
}
for(i in c(1:4)){
  df_input <- read_excel(paste('../lawdata/dust/2018/2018년 ',i,'분기.xlsx',sep=''))
  df_input <- df_input[colnames]
  df_concat <-rbind(df_concat,df_input)
}
df_concat
```


```{r}
#-----------------------------------------
#세종 만들기 
#----------------------------------------



df_concat <- df_concat %>% mutate(시도 = str_split(주소, "\\s", simplify = TRUE)[, 1])
df_concat <- df_concat %>% mutate(시군구 = str_split(주소, "\\s", simplify = TRUE)[, 2])


df_daejeon <- df_concat %>% filter(시도 == '대전')
df_chungju <- df_concat %>% filter(시군구 == '청주시')

df_sejong <- rbind(df_daejeon,df_chungju)
df_sejong <- df_sejong[c('PM10','PM25','지역','측정일시','시도','시군구')]
df_sejong  <- df_sejong %>% mutate(측정일시 = substr(측정일시,0,8))
df_sejong$시도 <- "세종"

df_sejong <- df_sejong %>% group_by(측정일시,시도) %>% summarise(PM10=mean(PM10,na.rm = TRUE),PM25=mean(PM25,na.rm = TRUE))
df_sejong

```


```{r include=FALSE}

#-----------------------------------------
#시도 코드 넣기 
#----------------------------------------

code <- c('42','41','43','44','30','47','48','45','46','11','28','27','31','29','26','49','36') 
name <- c('강원','경기','충북','충남','대전','경북','경남','전북','전남','서울','인천','대구','울산','광주','부산','제주','세종')
df_sido <- data.frame("code"=code,"name"=name)

#정제된 데이터 호출

df_2016<- read_csv("../lawdata/dust/2016년.csv",locale=locale('ko',encoding='euc-kr'))
df_2017<- read_csv("../lawdata/dust/2017년.csv",locale=locale('ko',encoding='euc-kr'))
df_2018<- read_csv("../lawdata/dust/2018년.csv",locale=locale('ko',encoding='euc-kr'))

df_concat <- rbind(df_2016,df_2017,df_2018)
df_concat

```


```{r}

df_sido$name <- as.character(df_sido$name)
df_concat <- inner_join(df_concat,df_sido,by=c("시도"="name"))



#날짜변환
df_concat  <- df_concat%>% mutate(측정일시 = substr(일시,0,8)) 
df_concat<- df_concat %>% select(-일시)


#세종데이터 넣기

df_concat <- inner_join(df_concat,df_sejong,by="측정일시")

df_concat$PM25.x <- ifelse(is.na(df_concat$PM25.x),df_concat$PM25.y,df_concat$PM25.x)
df_concat%>% filter(시도.x=='세종')
df_concat <- df_concat %>% select(-시도.y,-PM10.y,-PM25.y)

df_concat <- rename(df_concat,c(시도=시도.x,PM10=PM10.x,PM25=PM25.x)) 
df_concat

```


```{r}
#등급 매기기


df_concat$PM10등급 <- ifelse(df_concat$PM10 <= 30,1, 
                           ifelse(df_concat$PM10 <= 80,2,
                                  ifelse(df_concat$PM10 < 150,3,4)))

df_concat$PM25등급 <- ifelse(df_concat$PM25 <= 15,1, 
                           ifelse(df_concat$PM25 <= 50,2,
                                  ifelse(df_concat$PM25< 100,3,4)))

df_concat
```


```{r}
#미세먼지 데이터 저장
#write.csv(df_concat,file='refinedata/weather/dust_data.csv')
```


