---
---

```{r include=FALSE}
#-----------------------------------------
#데이터 가져오기
#----------------------------------------

df_medical <- NHIS_Data_2016_Fixed <- read_csv("../../lawdata/medical/NHIS_Data_2016_Fixed.csv",locale=locale('ko',encoding='euc-kr'))

```

```{r}
#-----------------------------------------
#요일로 정제
#----------------------------------------

df_medical <- df_medical %>% mutate(요양개시일자월별=paste(substring(요양개시일자,1,4),"-",substring(요양개시일자,5,6),sep=""))

df_medical

```



```{r}
#-----------------------------------------
#질병코드 변환
#----------------------------------------

ill<-function(x){

  res <- str_match_all(x,"([A-Z])([_]?)([0-9]{2})")
  
  n<- res[[1]][2]
  d<-res[[1]][3]
  t<-res[[1]][4]
 
    if ((t ==' ')|(is.na(t))){
    t <- 0
    }
    if((n ==' ')|(is.na(n))){
      return(x[1])
    }
    else if ((n == 'A') | (n =='B')){
      return ('AB')
    }
    else if((n == 'C')|((n == 'D')& (as.integer(t) <= 48))){
      return ('CD48')
    }
    else if (n == 'D'){
      return ('D50')
    }
    else if (n == 'H'){
      if (as.integer(t) < 60){
        return ('H59')
      }
    }
    else if (as.integer(t) >= 60){
      return ('H60')
    }
    else if ((n == 'S') | (n=='T')){
      return ('ST')
    }
    else if ((n == 'V') | (n == 'Y')){
      return ('VY')
    }
    else if (n[1] == 'F'){
      return ('F')
    }
    else{
      return (n)
    }
  
}



```


```{r}
#사용안함


# list <- c(df_medical$주상병코드)
# 
# clist <- list()
# length(list)
# 
# for(i in 1:length(list)){
#   clist <- append(clist,ill(list[i]))
# }
# 
# 
# 
# df_medical $ 질병코드 <- clist
```


```{r}
#-----------------------------------------
#데이터 저장
#----------------------------------------

df_medical <- df_medical[grep('J',df_medical$주상병코드),]
df_medical

#write.csv(df_medical,file = "refinedata/medical/NHIS_2016_J_Cases.csv")
```


