---
title: "Untitled"
output: html_document
---

##  2018년 분기별 세종,인천,충남,부산,경남,대구,울산,대전,광주

```{r}

load("../../../refinedata/analysis/analysis_total_Fixed.rda")
library(dplyr)
analysis_total_Fixed <- analysis_total_Fixed %>% dplyr::select(-발생건수,-`최고기온(°C)`,-`최저기온(°C)`)

```

```{r}

analysis_2018_quarter1 <- analysis_total_Fixed  %>% filter(substr(일시,1,7)=='2017-12'|substr(일시,1,7)=='2018-01'|substr(일시,1,7)=='2018-02')

analysis_2018_quarter1 <- analysis_2018_quarter1 %>% filter(시도 %in% c("세종","인천","충남","부산","경남","대구","울산","대전","광주")) 

analysis_2018_quarter1 <- analysis_2018_quarter1 %>% dplyr::select(-일시,-시도,-PM10등급,-PM25등급,-년도,-인구수,-`최다풍향(16방위)`)

analysis_2018_quarter1 <- analysis_2018_quarter1[-1]

analysis_2018_quarter1 <- as.data.frame(scale(analysis_2018_quarter1))


```


```{r}

analysis_2018_quarter2 <- analysis_total_Fixed %>% filter(substr(일시,1,7)=='2018-03'|substr(일시,1,7)=='2018-04'|substr(일시,1,7)=='2018-05')

analysis_2018_quarter2 <- analysis_2018_quarter2 %>% filter(시도 %in% c("세종","인천","충남","부산","경남","대구","울산","대전","광주")) 

analysis_2018_quarter2 <- analysis_2018_quarter2 %>% dplyr::select(-일시,-시도,-PM10등급,-PM25등급,-년도,-인구수,-`최다풍향(16방위)`)

analysis_2018_quarter2 <- analysis_2018_quarter2[-1]

analysis_2018_quarter2 <- as.data.frame(scale(analysis_2018_quarter2))

```


```{r}

analysis_2018_quarter3 <- analysis_total_Fixed %>% filter(substr(일시,1,7)=='2018-06'|substr(일시,1,7)=='2018-07'|substr(일시,1,7)=='2018-08')

analysis_2018_quarter3 <- analysis_2018_quarter3 %>% filter(시도 %in% c("세종","인천","충남","부산","경남","대구","울산","대전","광주"))

analysis_2018_quarter3 <- analysis_2018_quarter3 %>% dplyr::select(-일시,-시도,-PM10등급,-PM25등급,-년도,-인구수,-`최다풍향(16방위)`)

analysis_2018_quarter3 <- analysis_2018_quarter3[-1]

analysis_2018_quarter3 <- as.data.frame(scale(analysis_2018_quarter3))

```


```{r}

analysis_2018_quarter4 <- analysis_total_Fixed %>% filter(substr(일시,1,7)=='2018-09'|substr(일시,1,7)=='2018-10'|substr(일시,1,7)=='2018-11')

analysis_2018_quarter4 <- analysis_2018_quarter4 %>% filter(시도 %in% c("세종","인천","충남","부산","경남","대구","울산","대전","광주")) 

analysis_2018_quarter4 <- analysis_2018_quarter4 %>% dplyr::select(-일시,-시도,-PM10등급,-PM25등급,-년도,-인구수,-`최다풍향(16방위)`)

analysis_2018_quarter4 <- analysis_2018_quarter4[-1]

analysis_2018_quarter4 <- as.data.frame(scale(analysis_2018_quarter4))

```



```{r}

library(corrplot, quietly = TRUE)

corrplot(cor(analysis_2018_quarter1 ), method="circle")

```


```{r}
corrplot(cor(analysis_2018_quarter2 ), method="circle")

```


```{r}
corrplot(cor(analysis_2018_quarter3 ), method="circle")

```


```{r}
corrplot(cor(analysis_2018_quarter4 ), method="circle")

```

```{r}
cor(analysis_2018_quarter1 )

```


```{r}
cor(analysis_2018_quarter2 )

```

```{r}
cor(analysis_2018_quarter3 )

```

```{r}
cor(analysis_2018_quarter4 )

```


```{r}

library(MASS)


fitdata <- analysis_2018_quarter1
fit1 <- lm(발병률 ~ .,data = fitdata)
fit2 <- lm(발병률 ~ 1,data = fitdata)
stepAIC(fit2,direction="both",scope=list(upper=fit1,lower=fit2))

```

```{r}
fit <-  lm(formula = 발병률 ~ CO + SO2 + PM25 + PM10 + `강수 계속시간(hr)` + 
    `평균 현지기압(hPa)`, data =  analysis_2018_quarter1)

summary(fit)

```



```{r}
fitdata <- analysis_2018_quarter2 %>% dplyr::select(-`일 최심신적설(cm)`)
fit1 <- lm(발병률 ~ .,data = fitdata)
fit2 <- lm(발병률 ~ 1,data = fitdata)
stepAIC(fit2,direction="both",scope=list(upper=fit1,lower=fit2))

```

```{r}
fit <- lm(formula = 발병률 ~ CO + NO2 + PM25 + SO2 + `평균기온(°C)` + 
    `평균 현지기압(hPa)` + `강수 계속시간(hr)` + `일강수량(mm)` + 
    PM10, data = analysis_2018_quarter2)

summary(fit)

```


```{r}
fitdata <- analysis_2018_quarter3 %>% dplyr::select(-`일 최심신적설(cm)`)
fit1 <- lm(발병률 ~ .,data = fitdata)
fit2 <- lm(발병률 ~ 1,data = fitdata)
stepAIC(fit2,direction="both",scope=list(upper=fit1,lower=fit2))

```

```{r}
 fit <- lm(formula = 발병률 ~ CO + SO2 + PM25 + NO2 + O3 + `일강수량(mm)` + 
    `강수 계속시간(hr)`,,  
data = analysis_2018_quarter3)

summary(fit)

```


```{r}
fitdata <- analysis_2018_quarter4
fit1 <- lm(발병률  ~ .,data = fitdata)
fit2 <- lm(발병률 ~ 1,data = fitdata)
stepAIC(fit2,direction="both",scope=list(upper=fit1,lower=fit2))

```

```{r}
fit<-lm(formula = 발병률 ~ O3 + SO2 + CO + PM25 + PM10 + `평균기온(°C)` + 
    `강수 계속시간(hr)` + `일강수량(mm)`,  data = analysis_2018_quarter4)

summary(fit)

```

